/**
 * dsh-plugin-cheatsheet — 速查数据。
 * 按主题分类的开发者常用速查条目，条目刻意保持简洁（key + 一句话说明 + 可选命令）。
 */

export interface CheatEntry {
  /** 速查键：命令名 / 方法名 / 状态码 / 符号 */
  key: string
  /** 一句话说明（中文） */
  desc: string
  /** 可选：命令 / 代码片段 */
  code?: string
  /** 可选：补充提示 */
  note?: string
}

export interface CheatCategory {
  id: string
  title: string
  icon: string
  /** 分类一句话简介（可选） */
  desc?: string
  entries: CheatEntry[]
}

export const CHEATSHEET: CheatCategory[] = [
  {
    id: 'git',
    title: 'Git 常用命令',
    icon: '🔀',
    desc: '常用工作流：状态、提交、分支、合并、回滚、历史',
    entries: [
      { key: 'git status', desc: '查看工作区与暂存区状态' },
      { key: 'git add', desc: '暂存改动', code: 'git add <file> | git add -A' },
      { key: 'git commit', desc: '提交暂存改动', code: 'git commit -m "msg"' },
      { key: 'git push', desc: '推送本地提交到远程', code: 'git push origin <branch>' },
      { key: 'git pull', desc: '拉取并合并远程更新', code: 'git pull --rebase' },
      { key: 'git branch', desc: '列出/创建/删除分支', code: 'git branch -a / -d <name>' },
      { key: 'git checkout', desc: '切换分支或还原文件', code: 'git checkout <branch>' },
      { key: 'git switch', desc: '切换分支（新版推荐）', code: 'git switch -c <name>' },
      { key: 'git merge', desc: '合并分支到当前分支', code: 'git merge <branch>' },
      { key: 'git rebase', desc: '变基，改写提交历史', code: 'git rebase <branch> / -i HEAD~3' },
      { key: 'git stash', desc: '暂存未提交改动', code: 'git stash / stash pop' },
      { key: 'git log', desc: '查看提交历史', code: 'git log --oneline --graph' },
      { key: 'git diff', desc: '查看未暂存改动', code: 'git diff / --staged' },
      { key: 'git reset', desc: '撤销提交/回退指针', code: 'git reset --soft|--mixed|--hard <ref>' },
      { key: 'git revert', desc: '用新提交撤销某次提交', code: 'git revert <commit>' },
      { key: 'git cherry-pick', desc: '摘取指定提交到当前分支', code: 'git cherry-pick <commit>' },
      { key: 'git tag', desc: '打标签/发布标记', code: 'git tag v1.0.0' },
      { key: 'git fetch', desc: '只拉取远程更新不合并', code: 'git fetch origin' },
      { key: 'git remote', desc: '管理远程仓库', code: 'git remote -v / add / set-url' },
      { key: 'git blame', desc: '逐行查看文件修改者', code: 'git blame <file>' },
    ],
  },
  {
    id: 'commits',
    title: 'Git 提交规范',
    icon: '✍️',
    desc: 'Conventional Commits 类型与示例',
    entries: [
      { key: 'feat', desc: '新功能', code: 'feat: 新增用户登录' },
      { key: 'fix', desc: '修复 bug', code: 'fix: 修复空指针崩溃' },
      { key: 'docs', desc: '文档变更' },
      { key: 'style', desc: '格式（不影响代码逻辑）' },
      { key: 'refactor', desc: '重构（非新功能非修 bug）' },
      { key: 'perf', desc: '性能优化' },
      { key: 'test', desc: '增删测试' },
      { key: 'build', desc: '构建系统/外部依赖' },
      { key: 'ci', desc: 'CI 配置变更' },
      { key: 'chore', desc: '杂项（不涉及 src/test）' },
      { key: 'revert', desc: '回滚某次提交', code: 'revert: feat: 新增登录' },
      { key: 'BREAKING CHANGE', desc: '破坏性变更（脚注/正文标注）', code: 'feat!: 移除旧 API', note: '在 commit message 正文或 ! 标记' },
      { key: '示例', desc: '标准格式', code: 'feat(scope): subject\n\nbody\n\nfooter', note: 'type(scope): 主题，正文可选' },
    ],
  },
  {
    id: 'regex',
    title: '正则表达式',
    icon: '🎯',
    desc: '元字符、量词、分组断言与常用模式',
    entries: [
      { key: '.', desc: '任意单个字符（除换行）' },
      { key: '^ $', desc: '行首 / 行尾锚定', code: '^abc$' },
      { key: '* + ?', desc: '0+ / 1+ / 0或1 次' },
      { key: '{n,m}', desc: '至少 n 至多 m 次', code: 'a{2,4}' },
      { key: '[abc]', desc: '字符类，任一匹配' },
      { key: '[^abc]', desc: '排除字符类' },
      { key: '(x|y)', desc: '分组与或', code: '(jpg|png)' },
      { key: '(?:...)', desc: '非捕获分组' },
      { key: '(?=...)', desc: '正向先行断言', code: 'foo(?=bar)' },
      { key: '(?<=...)', desc: '正向后行断言', code: '(?<=foo)bar' },
      { key: '(?!...)', desc: '负向先行断言' },
      { key: '\\d \\w \\s', desc: '数字 / 字母数字下划线 / 空白', code: '\\D \\W \\S 为反向' },
      { key: '\\b', desc: '单词边界' },
      { key: '手机号', desc: '中国大陆手机号', code: '^1[3-9]\\d{9}$' },
      { key: '邮箱', desc: '常见邮箱格式', code: '^[\\w.-]+@[\\w-]+(\\.[\\w-]+)+$' },
      { key: 'URL', desc: 'http(s) 链接', code: '^https?://[^\\s]+$' },
      { key: '日期', desc: 'YYYY-MM-DD', code: '^\\d{4}-\\d{2}-\\d{2}$' },
      { key: 'IP', desc: 'IPv4 地址', code: '^(\\d{1,3}\\.){3}\\d{1,3}$' },
      { key: '中文', desc: '中文字符', code: '[\\u4e00-\\u9fa5]' },
      { key: '贪婪 vs 非贪婪', desc: '默认贪婪，加 ? 变非贪婪', code: 'a.*b 贪婪 / a.*?b 非贪婪' },
    ],
  },
  {
    id: 'http',
    title: 'HTTP 状态码',
    icon: '🌐',
    desc: '常用响应码含义速查',
    entries: [
      { key: '200', desc: 'OK 成功' },
      { key: '201', desc: 'Created 已创建（POST）' },
      { key: '204', desc: 'No Content 成功无返回体' },
      { key: '301', desc: '永久重定向' },
      { key: '302', desc: '临时重定向' },
      { key: '304', desc: 'Not Modified 缓存有效' },
      { key: '400', desc: 'Bad Request 请求错误' },
      { key: '401', desc: 'Unauthorized 未认证' },
      { key: '403', desc: 'Forbidden 无权限' },
      { key: '404', desc: 'Not Found 资源不存在' },
      { key: '405', desc: 'Method Not Allowed 方法不允许' },
      { key: '409', desc: 'Conflict 资源冲突' },
      { key: '422', desc: 'Unprocessable 语义错误（校验失败）' },
      { key: '429', desc: 'Too Many Requests 限流' },
      { key: '500', desc: '服务器内部错误' },
      { key: '502', desc: 'Bad Gateway 网关错误' },
      { key: '503', desc: 'Service Unavailable 服务不可用' },
      { key: '504', desc: 'Gateway Timeout 网关超时' },
    ],
  },
  {
    id: 'linux',
    title: 'Linux 命令',
    icon: '🐧',
    desc: '文件、进程、网络与服务的常用命令',
    entries: [
      { key: 'ls', desc: '列目录', code: 'ls -lah' },
      { key: 'cd', desc: '切换目录', code: 'cd ~ / .. / -' },
      { key: 'cp', desc: '复制', code: 'cp -r src dst' },
      { key: 'mv', desc: '移动/重命名', code: 'mv a b' },
      { key: 'rm', desc: '删除', code: 'rm -rf dir' },
      { key: 'mkdir', desc: '建目录', code: 'mkdir -p a/b/c' },
      { key: 'chmod', desc: '改权限', code: 'chmod 755 file / +x' },
      { key: 'chown', desc: '改属主', code: 'chown -R user:group dir' },
      { key: 'grep', desc: '文本搜索', code: 'grep -rn "word" .' },
      { key: 'find', desc: '查文件', code: 'find . -name "*.js" -mtime -7' },
      { key: 'sed', desc: '流式文本替换', code: "sed -i '' 's/a/b/g' f" },
      { key: 'awk', desc: '列处理', code: "awk '{print $1}' f" },
      { key: 'ps', desc: '进程列表', code: 'ps aux | grep x' },
      { key: 'kill', desc: '杀进程', code: 'kill -9 PID' },
      { key: 'df / du', desc: '磁盘空间 / 目录大小', code: 'df -h / du -sh *' },
      { key: 'top / htop', desc: '实时资源监控' },
      { key: 'tar', desc: '打包解包', code: 'tar -czvf x.tar.gz dir / -xzvf' },
      { key: 'ssh', desc: '远程登录', code: 'ssh user@host' },
      { key: 'scp', desc: '远程拷贝', code: 'scp f user@host:/path' },
      { key: 'curl', desc: 'HTTP 请求', code: 'curl -sSL URL / -X POST -d' },
      { key: 'systemctl', desc: '服务管理', code: 'systemctl status|restart svc' },
      { key: 'journalctl', desc: '日志查看', code: 'journalctl -u svc -f' },
      { key: 'ss / netstat', desc: '网络端口', code: 'ss -tlnp' },
      { key: 'lsof', desc: '占用端口的进程', code: 'lsof -i :8080' },
    ],
  },
  {
    id: 'docker',
    title: 'Docker 命令',
    icon: '🐳',
    desc: '镜像、容器与编排的常用命令',
    entries: [
      { key: 'docker build', desc: '构建镜像', code: 'docker build -t name:tag .' },
      { key: 'docker run', desc: '运行容器', code: 'docker run -d -p 8080:80 name' },
      { key: 'docker ps', desc: '列出运行中容器', code: 'docker ps -a' },
      { key: 'docker images', desc: '列出镜像' },
      { key: 'docker exec', desc: '进入容器执行', code: 'docker exec -it id sh' },
      { key: 'docker logs', desc: '查看日志', code: 'docker logs -f id' },
      { key: 'docker stop / start', desc: '停止 / 启动容器' },
      { key: 'docker rm', desc: '删除容器', code: 'docker rm id' },
      { key: 'docker rmi', desc: '删除镜像', code: 'docker rmi name:tag' },
      { key: 'docker pull / push', desc: '拉取 / 推送镜像' },
      { key: 'docker tag', desc: '打镜像标签', code: 'docker tag src dst:tag' },
      { key: 'docker compose up', desc: '启动编排', code: 'docker compose up -d' },
      { key: 'docker compose down', desc: '停止并删除编排资源' },
      { key: 'docker network', desc: '网络管理', code: 'docker network ls' },
      { key: 'docker volume', desc: '数据卷管理', code: 'docker volume ls / prune' },
      { key: 'docker prune', desc: '清理无用资源', code: 'docker system prune -a' },
      { key: 'docker cp', desc: '容器与主机互拷', code: 'docker cp f id:/path' },
    ],
  },
  {
    id: 'sql',
    title: 'SQL 速查',
    icon: '🗄️',
    desc: 'CRUD、连接、聚合与索引',
    entries: [
      { key: 'SELECT', desc: '查询', code: 'SELECT col FROM t WHERE x = 1' },
      { key: 'INSERT', desc: '插入', code: 'INSERT INTO t (a,b) VALUES (1,2)' },
      { key: 'UPDATE', desc: '更新', code: 'UPDATE t SET a=1 WHERE id=2' },
      { key: 'DELETE', desc: '删除', code: 'DELETE FROM t WHERE id=2' },
      { key: 'JOIN', desc: '连接查询', code: 'FROM a JOIN b ON a.id = b.aid', note: 'LEFT/RIGHT/INNER/FULL' },
      { key: 'GROUP BY', desc: '分组聚合', code: 'GROUP BY col' },
      { key: 'HAVING', desc: '分组后过滤（配 GROUP BY）', code: 'HAVING COUNT(*) > 1' },
      { key: 'ORDER BY', desc: '排序', code: 'ORDER BY col DESC' },
      { key: 'LIMIT', desc: '限制条数', code: 'LIMIT 10 OFFSET 20' },
      { key: 'LIKE', desc: '模糊匹配', code: "WHERE name LIKE '%x%'", note: '% 任意 / _ 单字符' },
      { key: 'IN', desc: '集合匹配', code: 'WHERE id IN (1,2,3)' },
      { key: 'BETWEEN', desc: '区间', code: 'WHERE n BETWEEN 1 AND 10' },
      { key: 'DISTINCT', desc: '去重', code: 'SELECT DISTINCT col' },
      { key: '子查询', desc: '嵌套查询', code: 'WHERE id IN (SELECT ...)' },
      { key: '索引', desc: '加速查询', code: 'CREATE INDEX idx ON t (col)' },
      { key: '事务', desc: '原子性操作', code: 'BEGIN; ... COMMIT; / ROLLBACK;' },
      { key: '聚合函数', desc: '常用聚合', code: 'COUNT / SUM / AVG / MAX / MIN' },
    ],
  },
  {
    id: 'terminal',
    title: '终端快捷键',
    icon: '⌨️',
    desc: 'macOS/Linux 终端快捷键',
    entries: [
      { key: 'Ctrl+C', desc: '中断当前命令' },
      { key: 'Ctrl+D', desc: 'EOF / 退出 shell' },
      { key: 'Ctrl+L', desc: '清屏' },
      { key: 'Ctrl+A / E', desc: '光标到行首 / 行尾' },
      { key: 'Ctrl+U / K', desc: '删除到行首 / 行尾' },
      { key: 'Ctrl+W', desc: '删除前一个单词' },
      { key: 'Ctrl+R', desc: '搜索历史命令' },
      { key: 'Ctrl+Z', desc: '挂起前台任务（fg 恢复）' },
      { key: 'Ctrl+←/→', desc: '按单词移动光标' },
      { key: 'Tab', desc: '自动补全' },
      { key: '!!', desc: '重复上一条命令', code: 'sudo !!' },
      { key: '!$', desc: '上一条命令的最后一个参数' },
      { key: 'history', desc: '查看命令历史', code: 'history | grep x' },
      { key: 'Ctrl+Shift+C/V', desc: '终端里复制/粘贴（部分环境）' },
    ],
  },
  {
    id: 'markdown',
    title: 'Markdown 语法',
    icon: '📝',
    desc: '常用 Markdown 语法',
    entries: [
      { key: '标题', desc: '1-6 级标题', code: '# H1 ## H2 ### H3' },
      { key: '加粗/斜体', desc: '强调', code: '**粗** *斜* ~~删除线~~' },
      { key: '链接', desc: '超链接', code: '[文字](https://url)' },
      { key: '图片', desc: '插图', code: '![alt](https://img.png)' },
      { key: '代码块', desc: '围栏代码块', code: '```js\ncode\n```' },
      { key: '行内代码', desc: '行内代码', code: '`code`' },
      { key: '列表', desc: '有序/无序', code: '- 项  /  1. 项' },
      { key: '任务列表', desc: '勾选清单', code: '- [x] 完成' },
      { key: '表格', desc: '表格', code: '| 列 | 列 |\n| --- | --- |' },
      { key: '引用', desc: '引用块', code: '> 引用内容' },
      { key: '分隔线', desc: '水平线', code: '---' },
      { key: '转义', desc: '转义特殊字符', code: '\\*literal\\*' },
    ],
  },
  {
    id: 'javascript',
    title: 'JavaScript 速查',
    icon: '🟨',
    desc: '高频数组、字符串、对象方法与异步',
    entries: [
      { key: 'map', desc: '映射数组', code: 'arr.map(x => x * 2)' },
      { key: 'filter', desc: '过滤数组', code: 'arr.filter(x => x > 0)' },
      { key: 'reduce', desc: '归约', code: 'arr.reduce((a,b) => a+b, 0)' },
      { key: 'find / findIndex', desc: '查找首个匹配', code: 'arr.find(x => x.id === 1)' },
      { key: 'includes', desc: '是否包含', code: 'arr.includes(v)' },
      { key: 'slice / splice', desc: '切片（不可变）/ 增删（可变）' },
      { key: 'split / join', desc: '字符串拆合', code: "'a,b'.split(',') / arr.join('-')" },
      { key: 'trim', desc: '去首尾空白', code: "' x '.trim()" },
      { key: '数组去重', desc: '去重', code: '[...new Set(arr)]' },
      { key: '对象展开', desc: '浅拷贝合并', code: '{ ...a, ...b }' },
      { key: '解构', desc: '解构赋值', code: 'const { a, b } = obj' },
      { key: '模板字符串', desc: '插值', code: '`hi ${name}`' },
      { key: 'async/await', desc: '异步', code: 'const r = await fetch(url)' },
      { key: '可选链', desc: '安全访问', code: 'obj?.a?.b' },
      { key: '空值合并', desc: '默认值', code: 'x ?? "default"' },
      { key: '时间戳转日期', desc: '格式化', code: 'new Date(ts).toISOString()' },
    ],
  },
  {
    id: 'python',
    title: 'Python 速查',
    icon: '🐍',
    desc: '高频语法、容器、文件与包管理',
    entries: [
      { key: '列表推导', desc: '列表推导式', code: '[x*2 for x in xs if x>0]' },
      { key: '字典推导', desc: '字典推导式', code: '{k: v for k, v in items}' },
      { key: 'enumerate', desc: '带下标遍历', code: 'for i, x in enumerate(xs)' },
      { key: 'zip', desc: '并行打包', code: 'zip(a, b)' },
      { key: 'lambda', desc: '匿名函数', code: 'lambda x: x + 1' },
      { key: 'map/filter', desc: '映射/过滤', code: 'list(map(f, xs))' },
      { key: 'f-string', desc: '字符串插值', code: 'f"hi {name}"' },
      { key: '字符串方法', desc: '常用方法', code: 'strip/split/join/replace/startswith' },
      { key: '文件读写', desc: 'with 上下文', code: 'with open("f") as f: f.read()' },
      { key: '切片', desc: '切片', code: 'xs[1:3] / xs[::-1] 反转' },
      { key: '异常处理', desc: 'try/except', code: 'try: ... except E as e: ...' },
      { key: '虚拟环境', desc: '隔离依赖', code: 'python -m venv .venv' },
      { key: 'pip', desc: '包管理', code: 'pip install pkg / freeze > req.txt' },
      { key: 'dict 方法', desc: '常用字典操作', code: 'd.get(k, dflt) / d.items()' },
    ],
  },
  {
    id: 'datetime',
    title: '日期时间 & 编码',
    icon: '🕐',
    desc: '日期格式、时间戳与编码转换',
    entries: [
      { key: '%Y-%m-%d', desc: '年-月-日', code: '2026-08-17' },
      { key: '%H:%M:%S', desc: '时:分:秒' },
      { key: '%A / %B', desc: '星期全名 / 月份全名' },
      { key: 'ISO 8601', desc: '标准时间格式', code: '2026-08-17T10:30:00Z' },
      { key: '时间戳', desc: 'Unix 秒/毫秒', code: 'Date.now() / int(time.time())' },
      { key: 'Base64 编码', desc: '二进制转文本', code: 'echo -n x | base64 / base64 -d' },
      { key: 'URL 编码', desc: '特殊字符转义', code: 'encodeURIComponent / urllib.parse.quote' },
      { key: 'JSON 美化', desc: '格式化输出', code: 'JSON.stringify(o, null, 2)' },
      { key: 'HTML 实体', desc: '转义', code: '&lt; &gt; &amp; &quot;' },
      { key: 'MD5 / SHA', desc: '哈希', code: 'md5sum / shasum -a 256' },
    ],
  },
]
